version: '3.8'

services:
  django_app:
    build: .
    command: gunicorn login.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" # Открываем порт для HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_static:/app/static:ro
      # Пробрасываем сертификаты (только для чтения)
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - django_app

volumes:
  static_static: